---
AWSTemplateFormatVersion: '2010-09-09'

Description: "Stack to deploy an application load balancer"

Parameters:
  AlbSecurityGroup:
    Description: "Security group for the application load balancer"
    Type: String

  PublicSubnet1:
    Description: "Public subnet 1"
    Type: String

  PublicSubnet2:
    Description: "Public subnet 2"
    Type: String

  ProjectName:
    Description: "Project name"
    Type: String

  Vpc:
    Description: "VPC"
    Type: String

Resources:
  Alb:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Type: application
      Name: !Join ["-", ["alb", !Ref ProjectName]]
      SecurityGroups:
        - !Ref AlbSecurityGroup
      Subnets:
        - !Ref PublicSubnet1
        - !Ref PublicSubnet2
      Tags:
        - Key: Name
          Value: !Ref ProjectName

  AlbTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Join [ "-", [ "alb", !Ref ProjectName, "target-group" ] ]
      Port: 80
      Protocol: HTTP
      TargetType: ip
      VpcId: !Ref Vpc
      HealthCheckIntervalSeconds: 60
      HealthCheckPath: /
      HealthCheckTimeoutSeconds: 30
      UnhealthyThresholdCount: 5
      HealthyThresholdCount: 2
      Matcher:
        HttpCode: "200,302"
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: "120"
        - Key: stickiness.enabled
          Value: "true"
        - Key: stickiness.type
          Value: lb_cookie
    DependsOn:
      - Alb

  AlbListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref AlbTargetGroup
      LoadBalancerArn: !Ref Alb
      Port: 80
      Protocol: HTTP

Outputs:
  AlbTargetGroup:
    Description: "Application load balancer target group"
    Value: !Ref AlbTargetGroup

  AlbListener:
    Description: "Application load balancer listener"
    Value: !Ref AlbListener